import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
import LeftSideBar from './Components/LeftSideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div>
          <Navbar></Navbar>
        </div>

        <div className='flex'>
          <div className='w-[345px]'>
            <LeftSideBar></LeftSideBar>
          </div>

          <div className='w-[1476px]'>
            {children}
          </div>
        </div>

      </body>
    </html>
  )
}
